version: '2'

services:
    config-server:
        container_name: config-server
        build:
            context: ./travel-mode-recommender-config-server/
        image: config-server:latest
        restart: always
        expose:
          - 8888
        ports:
          - 8888:8888
        networks:
          - spring-cloud-network
    tmr-api:
        container_name: tmr-api
        build:
          context: ./travel-mode-recommender-service/
        image: tmr-api:latest
        restart: always
        expose:
          - 8080
        ports:
          - 8080:8080
        networks:
          - spring-cloud-network
        links:
          - config-server:config-server
          - mysql:mysql
        depends_on:
          - config-server
          - mysql
    mysql:
        container_name: mysql
        build:
          context: ./data-store/
        image: mysql:latest
        restart: always
        expose:
          - 3306
        ports:
          - 3306:3306
        restart: always
        networks:
          - spring-cloud-network
        depends_on:
          - config-server
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tmr
          MYSQL_USER: user
          MYSQL_PASSWORD: root
        volumes:
          - mysql_data:/var/lib/mysql

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  mysql_data:
